
# Container Rabbit MQ
services:
    servidor_rabbit:
        image: rabbitmq:3.8.22-management
        container_name: rabbit-mq-server
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=123
